version: '3'
services:
  flask:
    image: stats-server
    runtime: nvidia
    restart: always
    environment:
      - FLASK_ENV=development
    expose:
      - 5000

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
